// Produits boutique Hormadi Anglet — basés sur les catalogues Macron, Pull-In, Promoglace & FanAvenue
export const demoProducts = [
  // ─── MAILLOTS (Macron) ─────────────────────────────────────────
  {
    id: 'prod-1',
    slug: 'maillot-domicile-2025-2026',
    name: 'Maillot Domicile 2025-2026',
    description: 'Maillot officiel Macron de l\'Hormadi Anglet pour la saison 2025-2026. Tissu Eco Fabric respirant, coupe slim fit, écusson brodé, sponsors officiels. Couleur vert foncé avec détails rouges.',
    price: 7999,
    category: 'maillots',
    imageUrl: '/images/boutique/maillot-domicile.svg',
    images: JSON.stringify(['/images/boutique/maillot-domicile.svg', '/images/boutique/maillot-domicile-dos.svg']),
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL', '3XL']),
    stock: 25,
    featured: true,
    published: true,
    badge: 'Nouveauté',
  },
  {
    id: 'prod-2',
    slug: 'maillot-exterieur-2025-2026',
    name: 'Maillot Extérieur 2025-2026',
    description: 'Maillot officiel Macron pour les déplacements. Design blanc avec accents verts et rouges, tissu Eco Fabric léger et respirant, finitions premium.',
    price: 7999,
    category: 'maillots',
    imageUrl: '/images/boutique/maillot-exterieur.svg',
    images: JSON.stringify(['/images/boutique/maillot-exterieur.svg']),
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL', '3XL']),
    stock: 18,
    featured: true,
    published: true,
    badge: 'Nouveauté',
  },
  {
    id: 'prod-3',
    slug: 'maillot-training-macron',
    name: 'Maillot Training Macron',
    description: 'Maillot d\'entraînement officiel Macron. Tissu technique léger et stretch, col rond, logo Hormadi et Macron brodés. Idéal pour le sport et les jours de match.',
    price: 3999,
    category: 'maillots',
    imageUrl: '/images/boutique/maillot-entrainement.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 30,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-4',
    slug: 'maillot-replique-enfant',
    name: 'Maillot Réplique Enfant',
    description: 'Réplique officielle Macron du maillot domicile pour les jeunes supporters. Même design que les joueurs, tailles enfant.',
    price: 5999,
    category: 'maillots',
    imageUrl: '/images/boutique/maillot-enfant.svg',
    images: null,
    sizes: JSON.stringify(['6 ans', '8 ans', '10 ans', '12 ans', '14 ans']),
    stock: 20,
    featured: true,
    published: true,
    badge: 'Junior',
  },

  // ─── TEXTILE Pull-In ──────────────────────────────────────────
  {
    id: 'prod-5',
    slug: 'hoodie-pull-in-hormadi-vert',
    name: 'Hoodie Pull-In Hormadi Vert',
    description: 'Hoodie officiel de la collection Pull-In x Hormadi. Capuche doublée, poche kangourou, logo Hormadi brodé sur la poitrine. 80% coton, 20% polyester.',
    price: 6500,
    category: 'textile',
    imageUrl: '/images/boutique/hoodie-vert.svg',
    images: null,
    sizes: JSON.stringify(['XS', 'S', 'M', 'L', 'XL', 'XXL']),
    stock: 20,
    featured: true,
    published: true,
    badge: 'Pull-In',
  },
  {
    id: 'prod-6',
    slug: 'hoodie-pull-in-hormadi-noir',
    name: 'Hoodie Pull-In Hormadi Noir',
    description: 'Hoodie noir de la collection Pull-In x Hormadi. Coupe oversized, intérieur molletonné, écusson Hormadi brodé. 80% coton, 20% polyester.',
    price: 6500,
    category: 'textile',
    imageUrl: '/images/boutique/hoodie-noir.svg',
    images: null,
    sizes: JSON.stringify(['XS', 'S', 'M', 'L', 'XL', 'XXL']),
    stock: 15,
    featured: false,
    published: true,
    badge: 'Pull-In',
  },
  {
    id: 'prod-7',
    slug: 'tshirt-pull-in-hormadi',
    name: 'T-Shirt Pull-In Hormadi',
    description: 'T-shirt officiel Pull-In x Hormadi. 100% coton, coupe regular, logo Hormadi sérigraphié sur la poitrine. Disponible en noir.',
    price: 3500,
    category: 'textile',
    imageUrl: '/images/boutique/tshirt-classique.svg',
    images: null,
    sizes: JSON.stringify(['XS', 'S', 'M', 'L', 'XL', 'XXL']),
    stock: 45,
    featured: false,
    published: true,
    badge: 'Pull-In',
  },
  {
    id: 'prod-8',
    slug: 'sweat-ligue-magnus-noir',
    name: 'Sweat Unisexe Ligue Magnus Noir',
    description: 'Sweat officiel Ligue Magnus aux couleurs de l\'Hormadi Anglet. Col rond, logo Hormadi et Ligue Magnus brodés. Molleton épais 350g.',
    price: 4999,
    category: 'textile',
    imageUrl: '/images/boutique/sweat-magnus.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 22,
    featured: true,
    published: true,
    badge: 'Best-seller',
  },
  {
    id: 'prod-9',
    slug: 'veste-softshell-macron',
    name: 'Veste Softshell Macron',
    description: 'Veste coupe-vent et déperlante officielle Macron. Col montant, fermeture zippée intégrale, logo Hormadi brodé. Parfaite pour les jours de match.',
    price: 7500,
    category: 'textile',
    imageUrl: '/images/boutique/veste-softshell.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 12,
    featured: true,
    published: true,
    badge: 'Macron',
  },
  {
    id: 'prod-10',
    slug: 'polo-macron-hormadi',
    name: 'Polo Macron Hormadi',
    description: 'Polo officiel Macron aux couleurs du club. Tissu piqué respirant, col boutonné, logos Macron et Hormadi brodés. Élégant pour les jours de match.',
    price: 4500,
    category: 'textile',
    imageUrl: '/images/boutique/polo-hormadi.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 18,
    featured: false,
    published: true,
    badge: 'Macron',
  },
  {
    id: 'prod-11',
    slug: 'jogging-macron-hormadi',
    name: 'Pantalon Training Macron',
    description: 'Pantalon d\'entraînement Macron officiel. Bas élastiqué, poches zippées, logo Hormadi brodé sur la cuisse. Tissu stretch confortable.',
    price: 4500,
    category: 'textile',
    imageUrl: '/images/boutique/jogging-hormadi.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 28,
    featured: false,
    published: true,
    badge: 'Macron',
  },
  {
    id: 'prod-12',
    slug: 'tshirt-femme-ligue-magnus',
    name: 'T-Shirt Femme Ligue Magnus',
    description: 'T-shirt femme officiel Ligue Magnus Hormadi Anglet. Coupe ajustée, 100% coton, logo Hormadi et Ligue Magnus imprimés. Noir.',
    price: 2999,
    category: 'textile',
    imageUrl: '/images/boutique/tshirt-femme.svg',
    images: null,
    sizes: JSON.stringify(['XS', 'S', 'M', 'L', 'XL']),
    stock: 30,
    featured: false,
    published: true,
    badge: null,
  },

  // ─── ACCESSOIRES (Pull-In, Promoglace, FanAvenue) ──────────────
  {
    id: 'prod-13',
    slug: 'casquette-pull-in-hormadi',
    name: 'Casquette Pull-In Hormadi',
    description: 'Casquette officielle Pull-In x Hormadi. Logo Hormadi brodé en 3D, taille ajustable snapback. 85% acrylique, 15% laine.',
    price: 3500,
    category: 'accessoires',
    imageUrl: '/images/boutique/casquette.svg',
    images: null,
    sizes: null,
    stock: 40,
    featured: true,
    published: true,
    badge: 'Pull-In',
  },
  {
    id: 'prod-14',
    slug: 'bonnet-hormadi',
    name: 'Bonnet Hormadi',
    description: 'Bonnet tricoté aux couleurs vert et rouge de l\'Hormadi. Pompon, patch Hormadi cousu, doublure polaire intérieure.',
    price: 2000,
    category: 'accessoires',
    imageUrl: '/images/boutique/bonnet.svg',
    images: null,
    sizes: null,
    stock: 35,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-15',
    slug: 'echarpe-supporter-hormadi',
    name: 'Écharpe Supporter Hormadi',
    description: 'L\'écharpe incontournable du supporter ! Bandes vertes et rouges tissées, inscriptions "HORMADI ANGLET" et "PAYS BASQUE". Acrylique doux.',
    price: 1500,
    category: 'accessoires',
    imageUrl: '/images/boutique/echarpe.svg',
    images: null,
    sizes: null,
    stock: 50,
    featured: true,
    published: true,
    badge: 'Indispensable',
  },
  {
    id: 'prod-16',
    slug: 'mug-ligue-magnus-hormadi',
    name: 'Mug Ligue Magnus Hormadi',
    description: 'Mug officiel Ligue Magnus en céramique 330ml avec logo Hormadi Anglet. Compatible lave-vaisselle et micro-ondes.',
    price: 1200,
    category: 'accessoires',
    imageUrl: '/images/boutique/mug.svg',
    images: null,
    sizes: null,
    stock: 60,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-17',
    slug: 'porte-cles-palet-hormadi',
    name: 'Porte-clés Palet Hormadi',
    description: 'Porte-clés en forme de mini palet de hockey avec le logo Hormadi gravé. Fabrication Promoglace. En caoutchouc souple.',
    price: 700,
    category: 'accessoires',
    imageUrl: '/images/boutique/porte-cles.svg',
    images: null,
    sizes: null,
    stock: 80,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-18',
    slug: 'mini-crosse-gardien-hormadi',
    name: 'Mini Crosse Gardien Hormadi',
    description: 'Mini crosse de gardien décorative aux couleurs de l\'Hormadi. Fabrication Promoglace. Idéale en objet déco ou cadeau.',
    price: 1500,
    category: 'accessoires',
    imageUrl: '/images/boutique/mini-crosse.svg',
    images: null,
    sizes: null,
    stock: 25,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-19',
    slug: 'drapeau-supporter-hormadi',
    name: 'Drapeau Supporter 150x90cm',
    description: 'Grand drapeau Hormadi Anglet Pays Basque pour les tribunes de la Patinoire de la Barre. Impression recto-verso, œillets métalliques.',
    price: 2500,
    category: 'accessoires',
    imageUrl: '/images/boutique/drapeau.svg',
    images: null,
    sizes: null,
    stock: 20,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-20',
    slug: 'palet-officiel-hormadi',
    name: 'Palet Officiel Hormadi',
    description: 'Palet de hockey sur glace officiel sérigraphié aux couleurs de l\'Hormadi Anglet. Parfait pour les collectionneurs.',
    price: 1000,
    category: 'accessoires',
    imageUrl: '/images/boutique/palet.svg',
    images: null,
    sizes: null,
    stock: 50,
    featured: false,
    published: true,
    badge: null,
  },

  // ─── ENFANT ───────────────────────────────────────────────────
  {
    id: 'prod-21',
    slug: 'tshirt-enfant-hormadi',
    name: 'T-Shirt Enfant Hormadi',
    description: 'T-shirt enfant 100% coton avec design Hormadi imprimé. Coupe confortable pour les petits supporters de la Patinoire de la Barre.',
    price: 1999,
    category: 'enfant',
    imageUrl: '/images/boutique/tshirt-enfant.svg',
    images: null,
    sizes: JSON.stringify(['4 ans', '6 ans', '8 ans', '10 ans', '12 ans']),
    stock: 35,
    featured: false,
    published: true,
    badge: null,
  },
  {
    id: 'prod-22',
    slug: 'hoodie-enfant-hormadi',
    name: 'Hoodie Enfant Hormadi',
    description: 'Hoodie enfant avec logo Hormadi brodé. Capuche doublée, poche kangourou, intérieur molletonné. Parfait pour les soirs de match.',
    price: 3999,
    category: 'enfant',
    imageUrl: '/images/boutique/hoodie-enfant.svg',
    images: null,
    sizes: JSON.stringify(['4 ans', '6 ans', '8 ans', '10 ans', '12 ans', '14 ans']),
    stock: 20,
    featured: true,
    published: true,
    badge: null,
  },
  {
    id: 'prod-23',
    slug: 'lot-echarpe-porte-cles',
    name: 'Lot Écharpe + Porte-clés',
    description: 'Pack duo Promoglace : écharpe supporter Hormadi + porte-clés palet. Le cadeau idéal pour un fan de l\'Hormadi.',
    price: 1800,
    category: 'enfant',
    imageUrl: '/images/boutique/lot-echarpe.svg',
    images: null,
    sizes: null,
    stock: 30,
    featured: false,
    published: true,
    badge: 'Pack',
  },

  // ─── COLLECTORS ───────────────────────────────────────────────
  {
    id: 'prod-24',
    slug: 'maillot-collector-50-ans',
    name: 'Maillot Collector 50 ans',
    description: 'Édition limitée célébrant les 50 ans du club. Maillot numéroté, packaging premium, certificat d\'authenticité. Design rétro exclusif.',
    price: 12999,
    category: 'collectors',
    imageUrl: '/images/boutique/maillot-collector.svg',
    images: null,
    sizes: JSON.stringify(['M', 'L', 'XL']),
    stock: 5,
    featured: true,
    published: true,
    badge: 'Édition limitée',
  },
  {
    id: 'prod-25',
    slug: 'pack-supporter-premium',
    name: 'Pack Supporter Premium',
    description: 'Le pack complet : maillot domicile Macron + écharpe + casquette Pull-In + mug Ligue Magnus. Économisez 20% par rapport à l\'achat séparé.',
    price: 9999,
    category: 'collectors',
    imageUrl: '/images/boutique/pack-supporter.svg',
    images: null,
    sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
    stock: 10,
    featured: true,
    published: true,
    badge: '-20%',
  },
  {
    id: 'prod-26',
    slug: 'photo-equipe-encadree-2025',
    name: 'Photo Équipe Encadrée 2025',
    description: 'Photo officielle de l\'équipe saison 2025-2026 dans un cadre bois 40x30cm. Édition limitée signée par les joueurs.',
    price: 4999,
    category: 'collectors',
    imageUrl: '/images/boutique/photo-equipe.svg',
    images: null,
    sizes: null,
    stock: 15,
    featured: false,
    published: true,
    badge: 'Signé',
  },
]
