import { NextRequest, NextResponse } from 'next/server'
import oldSiteRedirects from '@/data/old-site-redirects.json'

// The old WordPress site (pro.hormadi.fr) used root-level permalinks
// (pro.hormadi.fr/<slug>/), already indexed by Google for 316 articles. Now that
// hormadi.fr points here instead, those exact URLs would 404 without this map —
// redirecting them preserves that SEO equity instead of resetting it to zero.
// Generated by matching old-site posts to this DB's articles by publish timestamp;
// see the redirect-building commit for how to regenerate it if needed.
const REDIRECT_MAP: Record<string, string> = oldSiteRedirects

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl

  let target = REDIRECT_MAP[pathname]

  if (!target) {
    try {
      target = REDIRECT_MAP[decodeURIComponent(pathname)]
    } catch {
      // malformed percent-encoding — fall through, no redirect
    }
  }

  if (target) {
    return NextResponse.redirect(new URL(target, request.url), 301)
  }

  return NextResponse.next()
}

export const config = {
  // Skip _next assets, api routes and static images — the lookup itself is a cheap
  // O(1) object read, so there's no need to also restrict this to single-segment paths.
  matcher: ['/((?!api|_next|images|favicon.ico|icon.png|apple-icon.png).*)'],
}
